### ISSUE TITLE
Support of QGIS view rotation

### ISSUE THREAD

**Issue by geodrinx** [enricofer/go2streetview#10]
It would be great if go2streetview support the QGIS view rotation, introduced from QGIS 2.8.1.

Now, if view is rotated, the yellow line not corrispond to resulting streetview direction.

**Comment by enricofer** [comment]
Thanks for submission!
Fixed: https://github.com/enricofer/go2streetview/commit/b6c6a6fc67c409c3478b2f0d028aa373f8fb0c1e
Please test it and feed back.

**Comment by geodrinx** [comment]
Great !    It works.
But, I have another suggestion:  why not insert a button in  go2streetview   panel  to send the streetview heading rotation to QGIS ?
