### ISSUE TITLE
With floating window initial image appears at wrong size

### ISSUE THREAD

**Issue by RW-gis** [enricofer/go2streetview#13]
When I first open a streetview image it appears as a very small image in the corner of the floating window. 

I have go2streetview in a floating window on a second screen. 
QGIS 2.8.1 / go2streetview 6.2 / Windows 7

I open QGIS, then an existing project. A floating go2streetview window appears because I always use it like this. To make the plugin active I click the floating window. Then I click (and drag) on the map canvas to make a streetview image appear. It works, but the image only appears in the corner of the floating window. To fix this I can re-size the floating window or click (and drag) a second time on the map canvas.

The problem re-occurs at other times (not just when QGIS has just been opened), but I'm not clear exactly when.

![image](https://cloud.githubusercontent.com/assets/12844479/8453082/dbc8321c-1fe8-11e5-9cab-b3d1395e142f.png)

**Comment by enricofer** [comment]
The issue has already been fixed in the development version: https://github.com/enricofer/go2streetview/commit/7c45a4bd94ac5857258c400bafc1a1f83c97a791
[Download] (https://github.com/enricofer/go2streetview/archive/master.zip)
