### ISSUE TITLE
Network proxies (exclusions)

### ISSUE THREAD

**Issue by sebastian-r-schmidt** [enricofer/go2streetview#14]
From our company network we need to access external data sources through a authenticating proxy server. In QGIS Settings you can configure that proxy server. So far so good, go2streetview does work.

But additionally, we need to set proxy exclusions (urls not to connect to through the proxy) for our internal Geodata servers as these aren't reachable through the proxy.

Unfortunately, when activating go2streetview these exceptions aren't working anymore, so access to internal datasource is tried through the proxy and doesn't work anymore.

![proxy-settings](https://cloud.githubusercontent.com/assets/12548985/8615504/6ab2d1d8-26f3-11e5-9f6e-acdbf2002874.JPG)

Anything we can do about that?

**Comment by enricofer** [comment]
Hi Sebastian,
Unfortunately the api providing proxy connection to plugin doesn't support subnet exclusions: http://doc.qt.io/qt-5/qnetworkproxy.html
It's possible to support this dealing directly with the http connection but it is a little bit tricky workaround. But I exclude to solve the problem in the short term.... 
Regards

**Comment by sebastian-r-schmidt** [comment]
Hi, thanks for your fast reply.

Could it be helpful to use some of the functionality QGIS does priovide overcome with those limitiations in QT? It seems that http://www.qgis.org/api/classQgsNetworkAccessManager.html does deal correctly with proxy exclusions. Is it reachable through the python API?

Kind regards,
Sebastian

**Comment by enricofer** [comment]
Hi sebastian, perhaps you got it.
Qgis guys wide exposed API. It is possible to assign to QWebview the QgsNetworkAccessManager in two lines of code.  Evidently I was reinventing the wheel....
Please download, test and feedback: https://github.com/enricofer/go2streetview/archive/proxyingTest.zip
Thank you

**Comment by sebastian-r-schmidt** [comment]
This works for us - I can access go2StreetView through our proxy and the exclusions for internal datasources are taken into respect as well. Great, this is really hepful.

Would be glad to find this in an "official" go2streetView release.

Kind regards, Sebastian

**Comment by enricofer** [comment]
Maybe soon, I'm working on other features.
Regards
