### ISSUE TITLE
Error when installing: No module named resources

### ISSUE THREAD

**Issue by Tele-Pet** [enricofer/go2streetview#15]
I'm getting this error when I try to install it via Manage and Install Plugins window:  

>The plugin is broken.  Python said:
**No module named resources**

**Environment details**
Platform: Mac, 10.10.4
QGIS Version: Pisa, 2.10.1

**Comment by enricofer** [comment]
Oops
https://github.com/enricofer/go2streetview/commit/04bb4b1f3818798a9a104f1e5fdc32c28fc9a1c8

Thanks for submission.
