### ISSUE TITLE
Display the date of the image?

### ISSUE THREAD

**Issue by RW-gis** [enricofer/go2streetview#16]
Feature request: the streetview image should show the date of the image. Currently it is necessary to open an external browser window to see this.

**Comment by enricofer** [comment]
the feature has already been developed: https://github.com/enricofer/go2streetview/commit/368e8d1eab77f855466f9ecdf7395fdf15fa9b23
You can find it in master

**Comment by RW-gis** [comment]
Wonderful - keep up the good work, this tool is amazing and of daily use to me, and always attracts positive comments from colleagues,

**Comment by enricofer** [comment]
I'm happy to know you find it useful. Feel free to submit ideas about new features and other improvements

**Comment by RW-gis** [comment]
Enrico:
One area you might like to look at is how smoothly QGIS works with switching the use of the mouse cursor from/to go2streetview and other QGIS purposes such as dragging the map. I have a routine which I use… I click the drag button (hand symbol) to make the cursor drag the map - then I click the go2streetview window to tell the mouse to control go2streetview again. Sometimes this seems to get very messed up - I recently had to close and restart QGIS to get control of the mouse back from go2streetview so that I could drag the map. Often there are little problems - where I want to drag the map or select something but I accidentally get a new go2streetview image.

Perhaps there could be a second toolbar button beside the one which adds/removes the go2streetview window… which shows whether the mouse is currently controlling go2streetview?

Sorry that I cannot be more clear about when there are issues.

Robert Weetman
Project Officer, Signage and Mapping
Sustrans Scotland
Rosebery House
9 Haymarket Terrace
Edinburgh
EH12 5EZ

Direct: 0131 346 3015
Mobile: 07786 223728
Scotland office: 0131 346 1384
