### ISSUE TITLE
Mapillary streetview

### ISSUE THREAD

**Issue by baffioso** [enricofer/go2streetview#17]
Would it be possible to integrate Mapillary (www.mapillary.com/developer.html) sequences into go2streetview?

**Comment by enricofer** [comment]
No. I'm thinking to a brand new plugin.
Regards.

**Comment by enricofer** [comment]
Just pulled to github: https://github.com/enricofer/go2mapillary
Would you like to test it?

**Comment by baffioso** [comment]
Thank you so much. Will start testing
