### ISSUE TITLE
User-interface for Google Streetview is suddenly missing.

### ISSUE THREAD

**Issue by mzeedijk** [enricofer/go2streetview#18]
I think Google has changed something to the way the page is displayed so the Qt webbrowser object doesn't display the navigation arrows anymore. This seems to affect at least these versions of QGIS I tested with: 2.0.1, 2.8.6, 2.8.8, 2.14 incombination with these go2streetview plugin versions: 5.1, 6.2 and 6.5
If I open g2sv.html with the right parameters in a normal webbrowser (firefox or chrome) everything works as it should be.
Bing still works very well.
I tested on different OSes: Windows 7 64bit and Ubuntu 14.04LTS 64bit

**Comment by enricofer** [comment]
Thanks for submission!
It appears to be an issue of 3.24 current experimental release of streetview api.
I downgrade plugin to 3.23 and everything is right now.  I will submit soon a new release to the repository. For now download it from master: https://github.com/enricofer/go2streetview/archive/master.zip.
Regards

**Comment by mzeedijk** [comment]
Thank you very much for the very fast action. It is fixed!!

**Comment by enricofer** [comment]
http://plugins.qgis.org/plugins/go2streetview/version/7.0/

**Comment by mzeedijk** [comment]
Great. Thank you very much. Works like a charm.
