### ISSUE TITLE
Panning in Street View Window broken in QGIS 2.14

### ISSUE THREAD

**Issue by dpsspatial** [enricofer/go2streetview#19]
Hi there,

Noticing in QGIS 2.14 that it is not possible to pan the street view image in the window anymore.

Whenever the cursor is placed in the window, the image re-centers and the image can thus no longer pan in 360 degrees.

Let me know if I can provide more info. Thank you for this great plugin!!!

**Comment by enricofer** [comment]
I think this is the same issue: https://github.com/enricofer/go2streetview/issues/18
In this case simply upgrade from repository to the latest version.
Let me know if it goes

**Comment by dpsspatial** [comment]
Oh! Great! That worked perfectly. Thank you!!!
