### ISSUE TITLE
Crash at qgis closing

### ISSUE THREAD

**Issue by SergioGollino** [enricofer/go2streetview#20]
After some tests I see that go2streetview causes frequently a crash of qgis when i close the program. It generates a pgdump. tested on qgis 2.8.6-8 and qgis 2.14.1

Thank you!

**Comment by enricofer** [comment]
As far as I know this happens on Windows only, not on Linux and Mac os.
I will have a better look to signal disconnection on unload, but I fear it is a Qt webkit issue.
Thanks for submission!
