### ISSUE TITLE
Error displaying Streetview coverage

### ISSUE THREAD

**Issue by sumarin** [enricofer/go2streetview#22]
![captura_go2streetview](https://cloud.githubusercontent.com/assets/6768587/18382530/a0d4323c-7681-11e6-8867-4d42cb238d67.JPG)
Hi there

I Just discover this new feature in this plugin and I've tried only two days.
First day Everything OK but yestarday I see the coverage with strange colors and I can't see the blue lines that represent where google's car have passed.

After that I have tried on a new and different project but de error was the same.

I use QGIS 2.8.2 on a W7 machine

Nice job and thanks

**Comment by enricofer** [comment]
I can't reproduce issue on my testing machines, so I cannot help you.

**Comment by enricofer** [comment]
Could you check the new [master version](https://github.com/enricofer/go2streetview/archive/master.zip) inserting [Google Maps API key](https://github.com/enricofer/go2streetview/wiki/Release-7.2---Insert-Google-Maps-API-key) and report if the issue remains?

**Comment by sumarin** [comment]
Hi there,
At work I recently upgrade to Qgis 2.14 and remove Qgis 2.8 from the computer, and I haven't administration permissions for reinstall and try the new master version. I'm sorry.
At home I use OSGEOLIVE and don't have this problem.
With the 2.14 I haven't any problems.
Thanks and very useful plugin.....
