### ISSUE TITLE
Lot of latency in street view mode

### ISSUE THREAD

**Issue by tosage** [enricofer/go2streetview#25]
Hy,

Since wednesday of this week, a lot of my users experience a "big" latency when they move their cursor in the plugin.
I don't understand why beacause when they do the same thing on Street view in google chrome, they do not have the worry.

They use the 7.0 of the plugin in Qgis 2.1x.x

Any advices are appreciate :)

David

**Comment by enricofer** [comment]
At the moment I'm not finding anything strange in my test machines.
I leave the issue opened.

2016-11-18 10:13 GMT+01:00 tosage <notifications@github.com>:

**Comment by frugardc** [comment]
Our users are seeing the same thing.  Both 64 bit clients and 32 bit clients, using 2.14.  Anything I can do to assist testing?

**Comment by frugardc** [comment]
More specifically, the latency occurs when you "Click to go".  When that option is turned off, the speed is normal.  Of course, you cannot navigate down the street.

**Comment by SergioGollino** [comment]
I have the same strong latency problem.  Qgis 2.14.8

**Comment by Danewyn** [comment]
Same problem here, occurred around the same time as OP. My colleagues also have the problem. We are using the 7.0 version of the plugin, QGIS 2.14.4 on Windows 7 64-bits.

**Comment by enricofer** [comment]
I recently push a commit https://github.com/enricofer/go2streetview/commit/ffab3b18a0cd0b63581526226ebcf30bed628de9 to update api for fixing another issue
Please download and install [master ](https://github.com/enricofer/go2streetview/archive/master.zip)and check if this issue persists.

**Comment by Danewyn** [comment]
Unfortunately, the problem is still there for me.

**Comment by SergioGollino** [comment]
Still there for me too. Thanks for support!

**Comment by mespinos** [comment]
Same here. A lot of latency. Seems that it works a little bit faster when window size of street view is smaller.

**Comment by Danewyn** [comment]
Any news ?

Don't want to sound rude or to be oppressive but this function is just so useful in my everyday tasks. 

Thank you !

**Comment by kylesomerville** [comment]
Just to add to comments above - in recent weeks I've found the plugin to be verging on unusably slow.  Issue is reduced when using a smaller window.

**Comment by enricofer** [comment]
Could you check the new [master version](https://github.com/enricofer/go2streetview/archive/master.zip) inserting [Google Maps API key] (https://github.com/enricofer/go2streetview/wiki/Release-7.2---Insert-Google-Maps-API-key) and report if the issue remains?

**Comment by mespinos** [comment]
Enrico, 7.2 seems to work faster at my Mac and with big window size. Tomorrow I'll check it at my office (Windows with 2 screen, one used for G2SV)

**Comment by SergioGollino** [comment]
On W10 (2 screens) I continue to see a lot of latency even in a small window.

**Comment by enricofer** [comment]
In the new master release you can activate web inspector from plugin menu (it's above About item)
Could you please activate it and check for errors in console slot?

**Comment by SergioGollino** [comment]
Sure, here is the result. Thanks!

![console_error](https://cloud.githubusercontent.com/assets/18479662/21840545/60c68820-d7de-11e6-8b91-238842cce9a2.jpg)

**Comment by enricofer** [comment]
and network slot?

**Comment by SergioGollino** [comment]
Sorry I don't know how to export a text report. The network slot gives a quite long report.

![network_1](https://cloud.githubusercontent.com/assets/18479662/21841041/d18501ac-d7e0-11e6-9d1c-3002f1d62720.JPG)
![network_2](https://cloud.githubusercontent.com/assets/18479662/21841042/d185d4ce-d7e0-11e6-914d-8b2ff7d43c72.jpg)

**Comment by enricofer** [comment]
It suffits.
There is no network issue. All resources are downloaded with the expected latency.
There is no javascript issue. So I can't understand why you have latency in your instance.
Perhaps there is a Qt issue related to double display?
Could you try the same in a single display even with docked widget?

**Comment by Danewyn** [comment]
On my side (W7), results from the network and console inspector are quite similar. The problem stays on single and dual screens.

**Comment by SergioGollino** [comment]
No for me it's not related to dual screens. If I use the widget docked, there is no big latency, if I use the widget as a window the latency increases (on single and dual screen).

**Comment by enricofer** [comment]
So we can state that latency is due to large size plugin window.
In a typical urban context, 
for a 640px x 400px window, I'm measuring from web inspector about 30 requests and 2 Mb of download,
for a 1920px x 1024px window I get 70 requests and 3,5 Mb od download
Furthermore, more memory and processing resource is needed for panorama browsing.
Qt4 Webkit is showing his limits....
