### ISSUE TITLE
Error inserting Google Api key

### ISSUE THREAD

**Issue by AndreaBaro** [enricofer/go2streetview#27]
Good morning,
I put a wrong api key in the plugin form and now the plugin doesn't work.
If i try to use it, the window shows the image of the street for a little and immediately turn gray with a problem message.
How can i reset the key and insert the correct one?
Thanks

**Comment by enricofer** [comment]
Clicking on "About plugin" item under plugin menu the licence dialog re-appears, then you can insert the proper api key
![about](https://cloud.githubusercontent.com/assets/7544963/22290480/51900be6-e301-11e6-9be5-1fb109460bca.png)

**Comment by AndreaBaro** [comment]
Many thanks and compliments for the very good job
