### ISSUE TITLE
'Sorry! Something went wrong.' issue

### ISSUE THREAD

**Issue by RW-gis** [enricofer/go2streetview#28]
Since not long after upgrading to go2streetview 7.2 I have been unable to use this plugin. To begin with everything was fine - there were no problems with getting an API key and using the plugin. But now the go2streetview window displays the following message instead of a Streetview image:

"Sorry! Something went wrong. The page didn't load Google Maps correctly. See the JavaScript console for technical details"

This occurs with both QGIS 2.14 and QGIS 2.18 (on the same PC). I checked for conflicts with other plugins by disabling all the others but this didn't help.

The error is persistent and has completely stopped me using this plugin.

![capture](https://cloud.githubusercontent.com/assets/12844479/26398912/f496d22e-4072-11e7-8c39-56a074413ca2.JPG)

**Comment by enricofer** [comment]
Everything fine right now here.
Could you please provide the javascript console trace?
you can enable it clicking on "show web inspector for debugging"
![go2sv1](https://cloud.githubusercontent.com/assets/7544963/26399410/22b5645e-407d-11e7-81d2-c3fe7378df4b.jpg)
and then on console (... enlarging window if needed)
![go2sv2](https://cloud.githubusercontent.com/assets/7544963/26399438/3c62bb22-407d-11e7-894e-bea03a09891a.jpg)

**Comment by RW-gis** [comment]
The console output suggests to me that I may have used the wrong API code. It has a number displayed which is associated with a different service. I may have made a mistake as I use QGIS in more than one location. I'll check. 
![capture](https://cloud.githubusercontent.com/assets/12844479/26401535/59135abe-407e-11e7-91ca-84a163f31ed8.JPG)

**Comment by RW-gis** [comment]
Issue fixed. My mistake - sorry.
It may be helpful to note somewhere that this error suggests a problem with the API key.
