### ISSUE TITLE
API key expired

### ISSUE THREAD

**Issue by Komzpa** [enricofer/go2streetview#31]
![image](https://user-images.githubusercontent.com/810638/30320205-a5712ccc-97ba-11e7-88e5-7940a20ec397.png)

**Comment by enricofer** [comment]
Everything fine here.
If you don't provide more details about issue I can't help you.

**Comment by Komzpa** [comment]
Hi,

what can these details be?

I plainly installed the plugin. It shows the streetview, but crashes after seconds of interaction.
I open Web Inspector using the menu and the only error I can get from js console is that Map Key is expired.

Let me know what my options are.

Thanks for the plugin, when it works it helps a lot :)

**Comment by enricofer** [comment]
Did you have a look to api console: https://console.developers.google.com ?
I would try to get a new one. The [google api error messages page](https://developers.google.com/maps/documentation/javascript/error-messages)  reported that: 

> The API key included in the script element that loads the API has expired. You may need to generate a new API key in the Google API Console. 

anyway you are not the lonely: https://stackoverflow.com/questions/41631982/google-maps-expiredkeymaperror-with-recently-created-api-key
