### ISSUE TITLE
bing aerials do not open

### ISSUE THREAD

**Issue by jtrebilcock** [enricofer/go2streetview#33]
streetview works fine but the link to bing aerials just causes window to appear white

**Comment by enricofer** [comment]
It's due to API break. But recoverig the webapp with the same features it's a tough deal.

**Comment by SteveLowman** [comment]
Issue confirmed. It's a shame - this was a very useful facility.

**Comment by enricofer** [comment]
Migrating plugin to QGIS3 only, I dropped bing and switched to google maps oblique: https://github.com/enricofer/go2streetview/tree/master
I backported this feature to QGIS2 with some issues on wich I'm working on.
QGIS2 version is forked from master and you can download it from https://github.com/enricofer/go2streetview/tree/v7.4
Please download, test and report issues.

**Comment by jtrebilcock** [comment]
QGIS2 version returns the following error under manage and install plugins :
This plugin is broken
No module named go2streetview-7.4

**Comment by enricofer** [comment]
It appears a bad installation.
Try to replace the content of your existing go2streetview plugin folder
with the content of downloaded zip
https://gis.stackexchange.com/questions/127785/how-to-install-qgis-2-6-plugins-offline


2018-01-23 16:09 GMT+01:00 jtrebilcock <notifications@github.com>:

**Comment by SteveLowman** [comment]
I did what you suggest. But there is "ImportError: No module named resources_rc"
Full messagebox text attached.

[Go2StreetView could not load - messagebox text.txt](https://github.com/enricofer/go2streetview/files/1656699/Go2StreetView.could.not.load.-.messagebox.text.txt)

**Comment by enricofer** [comment]
Could you test this please: https://github.com/enricofer/go2streetview/archive/v7.4.zip
I can see from your exception trace that you are using qgis standalone under windows.
did you try the plugin with qgis from osgeo4w installer?

**Comment by SteveLowman** [comment]
Still the same error, or very similar, as attached.
This is now in the official plugin repository, so my colleagues are also now receiving the same error.

I only use the standalone LTR. I am not currently working as a developer, so I do not use the osgeo4w installer.

[Go2StreetView could not load - messagebox text 29012018.txt](https://github.com/enricofer/go2streetview/files/1673012/Go2StreetView.could.not.load.-.messagebox.text.29012018.txt)

**Comment by enricofer** [comment]
Could you please confirm that this does not throw exceptions: https://github.com/enricofer/go2streetview/archive/v7.5.zip

**Comment by SteveLowman** [comment]
Hi Enrico.
Sorry, but still getting a similar exception, as attached.

[Go2StreetView could not load - messagebox text 29012018b.txt](https://github.com/enricofer/go2streetview/files/1674298/Go2StreetView.could.not.load.-.messagebox.text.29012018b.txt)

**Comment by SteveLowman** [comment]
Also, it might have done something strange to my OpenLayers plugin. I don't understand this, but the attached image shows that my plugin manager is getting confused, showing the Go2StreetView description on the OpenLayers plugin manager page.

![openlayers plugin screenshot](https://user-images.githubusercontent.com/8450382/35521074-bd92d364-0510-11e8-94af-8030e2915e83.png)

**Comment by SteveLowman** [comment]
Sorry, deleted previous comments, where I must have pasted into the wrong plugin folder.
This time, there is no Python exception, but instead, it thinks this is version 8, not 7.5.

![openlayers plugin screenshot](https://user-images.githubusercontent.com/8450382/35521549-f2f2e9c6-0511-11e8-8351-acdd31c855b7.png)

**Comment by enricofer** [comment]
Sorry, I confused forks and I messed it... Now it's ready:  https://github.com/enricofer/go2streetview/archive/v7.5.zip

**Comment by enricofer** [comment]
I received a PR to solve the issue in another way: https://github.com/enricofer/go2streetview/pull/34
Please, Could you test it? https://github.com/enricofer/go2streetview/archive/v7.4.zip

**Comment by SteveLowman** [comment]
Yes, the #34 works. The resolution of the Google aerial photography is very low with a heavily pixelated image until you zoom out. Bing aerial has always had higher resolution photography. However, this version is now working without any exceptions, thank you.

**Comment by enricofer** [comment]
well, I will publish it. The aerial imagery q

2018-01-30 10:43 GMT+01:00 SteveLowman <notifications@github.com>:

**Comment by agiudiceandrea** [comment]
New version of https://github.com/enricofer/go2streetview/archive/v7.4.zip works with QGIS 2.18.16 64 bit standalone on Windows 7 SP1 64 bit.
There is only a warning in the Python warning tab of the Log messages panel when the plugin is enabled:

```
warning:C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\PyQt4\uic\uiparser.py:844: PendingDeprecationWarning: This method will be removed in future versions.  Use 'elem.iter()' or 'list(elem.iter())' instead.
			  for include in elem.getiterator("include"):
			
			traceback:  File "<string>", line 1, in <module>
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
			    plugins[packageName] = package.classFactory(iface)
			  File "C:/Users/Andrea/.qgis2/python/plugins\go2streetview\__init__.py", line 31, in classFactory
			    from go2streetview import go2streetview
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/Andrea/.qgis2/python/plugins\go2streetview\go2streetview.py", line 33, in <module>
			    from go2streetviewDialog import go2streetviewDialog, dumWidget,snapshotLicenseDialog, infobox
			  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/Andrea/.qgis2/python/plugins\go2streetview\go2streetviewDialog.py", line 37, in <module>
			    MAIN_DIALOG_CLASS, _ = uic.loadUiType(os.path.join(os.path.dirname(__file__), 'ui_go2streetview.ui'))
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\PyQt4\uic\__init__.py", line 210, in loadUiType
			    winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports, resource_suffix)
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\PyQt4\uic\Compiler\compiler.py", line 139, in compileUi
			    w = self.parse(input_stream, resource_suffix)
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\PyQt4\uic\uiparser.py", line 933, in parse
			    actor(elem)
			  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\PyQt4\uic\uiparser.py", line 844, in readResources
			    for include in elem.getiterator("include"):
```

**Comment by SteveLowman** [comment]
Hi Enrico. Did you publish the corrected one? It seemed to work when I first reinstalled, but now I have restarted the application and still getting the same stack trace, as attached.

[Go2StreetView could not load - messagebox text 30012018a.txt](https://github.com/enricofer/go2streetview/files/1677754/Go2StreetView.could.not.load.-.messagebox.text.30012018a.txt)

**Comment by enricofer** [comment]
I have not published it yet. I will name the new release v7.4.1

**Comment by enricofer** [comment]
published now: 
Plugin go2streetview approval by pcav.
The plugin version "[481] go2streetview 7.4.1" is now approved
Link: http://plugins.qgis.org/plugins/go2streetview/

**Comment by agiudiceandrea** [comment]
go2streetview 7.4.1 works, but remain the Python warning reported in my previous comment.

**Comment by enricofer** [comment]
I'm not worried about it.  It is related to PyQt4 uic module and I can't do nothing to fix it.
