### ISSUE TITLE
gotostreetview 8.0 (QGIS3-dev) -- AttributeError: type object 'QgsMessageLog' has no attribute 'INFO'

### ISSUE THREAD

**Issue by denchat** [enricofer/go2streetview#35]
When releasing left button after locating a POV camera,

> An error has occurred while executing Python code: 
> 
> AttributeError: type object 'QgsMessageLog' has no attribute 'INFO' 
> Traceback (most recent call last):
>   File "C:/Users/\<User\>/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2streetview\go2streetview.py", line 678, in canvasReleaseEvent
>     self.openSVDialog()
>   File "C:/Users/\<User\>/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2streetview\go2streetview.py", line 704, in openSVDialog
>     core.QgsMessageLog.logMessage(QtCore.QUrl(self.gswDialogUrl).toString(), tag="go2streetview", level=core.QgsMessageLog.INFO)
> AttributeError: type object 'QgsMessageLog' has no attribute 'INFO'
> 
> Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
> QGIS version: 2.99.0-Master Master, b6ad920404 
> 
> Python Path:
> C:/PROGRA\~1/QGIS3\~1.0/apps/qgis-dev/./python
> C:/Users\/\<User\>\/AppData/Roaming/QGIS/QGIS3\profiles\default/python
> C:/Users\/\<User\>\/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
> C:/PROGRA\~1/QGIS3\~1.0/apps/qgis-dev/./python/plugins
> C:\PROGRA\~1\QGIS3\~1.0\bin\python36.zip
> C:\PROGRA\~1\QGIS3\~1.0\apps\Python36\DLLs
> C:\PROGRA\~1\QGIS3\~1.0\apps\Python36\lib
> C:\PROGRA\~1\QGIS3\~1.0\bin
> C:\PROGRA\~1\QGIS3\~1.0\apps\Python36
> C:\PROGRA\~1\QGIS3\~1.0\apps\Python36\lib\site-packages
> C:/Users/\<User\>/AppData/Roaming/QGIS/QGIS3\profiles\default/python
> C:/Users/\<User\>/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2streetview
> C:\Users\\<User\>\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\go2streetview\res
> \<ProjectPath\>
> C:\/Users\/\<User\>\/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2streetview
> C:\/Users\/\<User\>\/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2mapillary
> C:\Users\\<User\>\\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\go2mapillary\extlibs

It seems that gotomapillary has the same issue also.

I install QGIS from OSGeo4Win/QGIS-dev.

Do I configure something wrong?

**Comment by enricofer** [comment]
there is a recent api break: https://github.com/qgis/QGIS/commit/3dc3d9d1b22f38cdccedb72683c077a219cda021#diff-e7716c5d7d0e03be531ed223167df03a

**Comment by denchat** [comment]
The major release due in a week, perhaps there might be some more naming decisions during this period of time then.
