### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by antoniusz** [enricofer/go2streetview#36]
I got this error on startup, but the plugin is working.

Hiba történt a Python kód végrehajtása közben: 

AttributeError: 'NoneType' object has no attribute 'geometryType' 
Traceback (most recent call last):
  File "/home/toni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2streetview/go2streetview.py", line 374, in infoLayerDefinedAction
    self.writeInfoBuffer(self.transformToCurrentSRS(actualPoint))
  File "/home/toni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2streetview/go2streetview.py", line 738, in writeInfoBuffer
    if self.infoBoxManager.getInfolayer().geometryType() == core.QgsWkbTypes.PointGeometry:
AttributeError: 'NoneType' object has no attribute 'geometryType'

Python verzió: 3.6.4+ (default, Feb 12 2018, 08:25:03) [GCC 7.3.0] 
QGIS verzió 3.0.0-Girona Girona, ad6491d

**Comment by enricofer** [comment]
Did you tried to disable infolayer from "add info layer" menu and restart qgis ?
![screenshot 2018-03-16 12 14 23](https://user-images.githubusercontent.com/7544963/37518032-ca10865a-2913-11e8-86b6-ba0f7a063b3d.png)

**Comment by antoniusz** [comment]
Yes, and the error message disappeared.

**Comment by enricofer** [comment]
I don't get errors. Can you help me to replicate issue?

**Comment by antoniusz** [comment]
Yes., What should i do?

**Comment by enricofer** [comment]
simply list the actions that bring to error, so I can replicate and understand the issue and fix it

**Comment by antoniusz** [comment]
The cause of the error was, that I enabled the option, but haven't defined a layer for it.
