### ISSUE TITLE
QGIS 2.18 Browser display problem

### ISSUE THREAD

**Issue by syseliak** [enricofer/go2streetview#42]
Once yo click on desired location, the streetview is not displayed. Some details here: 
https://gis.stackexchange.com/questions/272656/qgis-go2streetview-browser-display-problem/302614#302614
![4yxtk](https://user-images.githubusercontent.com/43641261/48481615-27cd1680-e806-11e8-9701-566f7c16ec63.jpg)

**Comment by enricofer** [comment]
Everything fine right now here.
Could you please provide the javascript console trace?
you can enable it clicking on "show web inspector for debugging"
![](https://cloud.githubusercontent.com/assets/7544963/26399410/22b5645e-407d-11e7-81d2-c3fe7378df4b.jpg)
and then on console tab
![](https://cloud.githubusercontent.com/assets/7544963/26399438/3c62bb22-407d-11e7-894e-bea03a09891a.jpg)

**Comment by syseliak** [comment]
Hi Enric,

I got this:

g2gm.html:53loadScript
g2gm.html:75GetMap
g2gm.html:126
<div id=​"icona" style=​"border-top-style:​ none;​ border-right-style:​ none;​ border-bottom-style:​ none;​ border-left-style:​ none;​ border-top-width:​ 0px;​ border-right-width:​ 0px;​ border-bottom-width:​ 0px;​ border-left-width:​ 0px;​ position:​ absolute;​ left:​ 348px;​ top:​ 211.5px;​ width:​ 32px;​ height:​ 32px;​ ">​…​</div>​
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2224px%22%20height%3D%2224px%22%20viewBox%3D%220%200%2024%2024%22%20fill%3D%22%23000000%22%3E%0A%20%20%20%20%3Cpath%20d%3D%22M19%206.41L17.59%205%2012%2010.59%206.41%205%205%206.41%2010.59%2012%205%2017.59%206.41%2019%2012%2013.41%2017.59%2019%2019%2017.59%2013.41%2012z%22%2F%3E%0A%20%20%20%20%3Cpath%20d%3D%22M0%200h24v24H0z%22%20fill%3D%22none%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%200%2018%2018%22%3E%0A%20%20%3Cpolygon%20fill%3D%22%23666%22%20points%3D%2218%2C7%2011%2C7%2011%2C0%207%2C0%207%2C7%200%2C7%200%2C11%207%2C11%207%2C18%2011%2C18%2011%2C11%2018%2C11%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%200%2018%2018%22%3E%0A%20%20%3Cpolygon%20fill%3D%22%23333%22%20points%3D%2218%2C7%2011%2C7%2011%2C0%207%2C0%207%2C7%200%2C7%200%2C11%207%2C11%207%2C18%2011%2C18%2011%2C11%2018%2C11%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%200%2018%2018%22%3E%0A%20%20%3Cpolygon%20fill%3D%22%23111%22%20points%3D%2218%2C7%2011%2C7%2011%2C0%207%2C0%207%2C7%200%2C7%200%2C11%207%2C11%207%2C18%2011%2C18%2011%2C11%2018%2C11%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%200%2018%2018%22%3E%0A%20%20%3Cpath%20fill%3D%22%23666%22%20d%3D%22M0%2C7h18v4H0V7z%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%200%2018%2018%22%3E%0A%20%20%3Cpath%20fill%3D%22%23333%22%20d%3D%22M0%2C7h18v4H0V7z%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%200%2018%2018%22%3E%0A%20%20%3Cpath%20fill%3D%22%23111%22%20d%3D%22M0%2C7h18v4H0V7z%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2224%22%20height%3D%2222%22%20viewBox%3D%220%200%2024%2022%22%3E%0A%20%20%3Cpath%20fill%3D%22%23666%22%20fill-rule%3D%22evenodd%22%20d%3D%22M20%2010c0-5.52-4.48-10-10-10s-10%204.48-10%2010v5h5v-5c0-2.76%202.24-5%205-5s5%202.24%205%205v5h-4l6.5%207%206.5-7h-4v-5z%22%20clip-rule%3D%22evenodd%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2224%22%20height%3D%2222%22%20viewBox%3D%220%200%2024%2022%22%3E%0A%20%20%3Cpath%20fill%3D%22%23333%22%20fill-rule%3D%22evenodd%22%20d%3D%22M20%2010c0-5.52-4.48-10-10-10s-10%204.48-10%2010v5h5v-5c0-2.76%202.24-5%205-5s5%202.24%205%205v5h-4l6.5%207%206.5-7h-4v-5z%22%20clip-rule%3D%22evenodd%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2224%22%20height%3D%2222%22%20viewBox%3D%220%200%2024%2022%22%3E%0A%20%20%3Cpath%20fill%3D%22%23111%22%20fill-rule%3D%22evenodd%22%20d%3D%22M20%2010c0-5.52-4.48-10-10-10s-10%204.48-10%2010v5h5v-5c0-2.76%202.24-5%205-5s5%202.24%205%205v5h-4l6.5%207%206.5-7h-4v-5z%22%20clip-rule%3D%22evenodd%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218px%22%20height%3D%2216px%22%20viewBox%3D%220%200%2018%2016%22%3E%0A%20%20%3Cpath%20fill%3D%22%23666%22%20d%3D%22M0%2C16h8V9H0V16z%20M10%2C16h8V9h-8V16z%20M0%2C7h8V0H0V7z%20M10%2C0v7h8V0H10z%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218px%22%20height%3D%2216px%22%20viewBox%3D%220%200%2018%2016%22%3E%0A%20%20%3Cpath%20fill%3D%22%23333%22%20d%3D%22M0%2C16h8V9H0V16z%20M10%2C16h8V9h-8V16z%20M0%2C7h8V0H0V7z%20M10%2C0v7h8V0H10z%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218px%22%20height%3D%2216px%22%20viewBox%3D%220%200%2018%2016%22%3E%0A%20%20%3Cpath%20fill%3D%22%23111%22%20d%3D%22M0%2C16h8V9H0V16z%20M10%2C16h8V9h-8V16z%20M0%2C7h8V0H0V7z%20M10%2C0v7h8V0H10z%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2222px%22%20height%3D%2213px%22%20viewBox%3D%220%200%2022%2013%22%3E%0A%20%20%3Cpath%20fill%3D%22%23666%22%20d%3D%22M2.75%2C5H10V0H4.4L2.75%2C5z%20M0%2C13h10V7H2L0%2C13z%20M20%2C7h-8v6h10L20%2C7z%20M17.6%2C0H12v5h7.25L17.6%2C0z%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2222px%22%20height%3D%2213px%22%20viewBox%3D%220%200%2022%2013%22%3E%0A%20%20%3Cpath%20fill%3D%22%23333%22%20d%3D%22M2.75%2C5H10V0H4.4L2.75%2C5z%20M0%2C13h10V7H2L0%2C13z%20M20%2C7h-8v6h10L20%2C7z%20M17.6%2C0H12v5h7.25L17.6%2C0z%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2222px%22%20height%3D%2213px%22%20viewBox%3D%220%200%2022%2013%22%3E%0A%20%20%3Cpath%20fill%3D%22%23111%22%20d%3D%22M2.75%2C5H10V0H4.4L2.75%2C5z%20M0%2C13h10V7H2L0%2C13z%20M20%2C7h-8v6h10L20%2C7z%20M17.6%2C0H12v5h7.25L17.6%2C0z%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.

**Comment by fabio-pisto** [comment]
Hi,
too me have this problem today

**Comment by fabio-pisto** [comment]
i got this
g2gm.html:53loadScript
g2gm.html:75GetMap
g2gm.html:125
<div id=​"icona" style=​"border-top-style:​ none;​ border-right-style:​ none;​ border-bottom-style:​ none;​ border-left-style:​ none;​ border-top-width:​ 0px;​ border-right-width:​ 0px;​ border-bottom-width:​ 0px;​ border-left-width:​ 0px;​ position:​ absolute;​ left:​ 273px;​ top:​ 380.5px;​ width:​ 32px;​ height:​ 32px;​ ">​…​</div>​
5g2gm.html:141
<div id=​"icona" style=​"border-top-style:​ none;​ border-right-style:​ none;​ border-bottom-style:​ none;​ border-left-style:​ none;​ border-top-width:​ 0px;​ border-right-width:​ 0px;​ border-bottom-width:​ 0px;​ border-left-width:​ 0px;​ position:​ absolute;​ left:​ 273px;​ top:​ 380.5px;​ width:​ 32px;​ height:​ 32px;​ ">​…​</div>​
2g2gm.html:154undefined
4g2gm.html:141
<div id=​"icona" style=​"border-top-style:​ none;​ border-right-style:​ none;​ border-bottom-style:​ none;​ border-left-style:​ none;​ border-top-width:​ 0px;​ border-right-width:​ 0px;​ border-bottom-width:​ 0px;​ border-left-width:​ 0px;​ position:​ absolute;​ left:​ 273px;​ top:​ 380.5px;​ width:​ 32px;​ height:​ 32px;​ ">​…​</div>​

**Comment by enricofer** [comment]
I can't replicate the issue on my systems.  Looking to console trace this does not appear as a plugin related issue.

**Comment by CbassettEGR** [comment]
Same issue here. Plugin was working fine on 11/12 and stopped working on 11/13.

data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2224px%22%20height%3D%2224px%22%20viewBox%3D%220%200%2024%2024%22%20fill%3D%22%23000000%22%3E%0A%20%20%20%20%3Cpath%20d%3D%22M19%206.41L17.59%205%2012%2010.59%206.41%205%205%206.41%2010.59%2012%205%2017.59%206.41%2019%2012%2013.41%2017.59%2019%2019%2017.59%2013.41%2012z%22%2F%3E%0A%20%20%20%20%3Cpath%20d%3D%22M0%200h24v24H0z%22%20fill%3D%22none%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%200%2018%2018%22%3E%0A%20%20%3Cpolygon%20fill%3D%22%23666%22%20points%3D%2218%2C7%2011%2C7%2011%2C0%207%2C0%207%2C7%200%2C7%200%2C11%207%2C11%207%2C18%2011%2C18%2011%2C11%2018%2C11%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%200%2018%2018%22%3E%0A%20%20%3Cpolygon%20fill%3D%22%23333%22%20points%3D%2218%2C7%2011%2C7%2011%2C0%207%2C0%207%2C7%200%2C7%200%2C11%207%2C11%207%2C18%2011%2C18%2011%2C11%2018%2C11%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%200%2018%2018%22%3E%0A%20%20%3Cpolygon%20fill%3D%22%23111%22%20points%3D%2218%2C7%2011%2C7%2011%2C0%207%2C0%207%2C7%200%2C7%200%2C11%207%2C11%207%2C18%2011%2C18%2011%2C11%2018%2C11%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%200%2018%2018%22%3E%0A%20%20%3Cpath%20fill%3D%22%23666%22%20d%3D%22M0%2C7h18v4H0V7z%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%200%2018%2018%22%3E%0A%20%20%3Cpath%20fill%3D%22%23333%22%20d%3D%22M0%2C7h18v4H0V7z%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%200%2018%2018%22%3E%0A%20%20%3Cpath%20fill%3D%22%23111%22%20d%3D%22M0%2C7h18v4H0V7z%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2224%22%20height%3D%2222%22%20viewBox%3D%220%200%2024%2022%22%3E%0A%20%20%3Cpath%20fill%3D%22%23666%22%20fill-rule%3D%22evenodd%22%20d%3D%22M20%2010c0-5.52-4.48-10-10-10s-10%204.48-10%2010v5h5v-5c0-2.76%202.24-5%205-5s5%202.24%205%205v5h-4l6.5%207%206.5-7h-4v-5z%22%20clip-rule%3D%22evenodd%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2224%22%20height%3D%2222%22%20viewBox%3D%220%200%2024%2022%22%3E%0A%20%20%3Cpath%20fill%3D%22%23333%22%20fill-rule%3D%22evenodd%22%20d%3D%22M20%2010c0-5.52-4.48-10-10-10s-10%204.48-10%2010v5h5v-5c0-2.76%202.24-5%205-5s5%202.24%205%205v5h-4l6.5%207%206.5-7h-4v-5z%22%20clip-rule%3D%22evenodd%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2224%22%20height%3D%2222%22%20viewBox%3D%220%200%2024%2022%22%3E%0A%20%20%3Cpath%20fill%3D%22%23111%22%20fill-rule%3D%22evenodd%22%20d%3D%22M20%2010c0-5.52-4.48-10-10-10s-10%204.48-10%2010v5h5v-5c0-2.76%202.24-5%205-5s5%202.24%205%205v5h-4l6.5%207%206.5-7h-4v-5z%22%20clip-rule%3D%22evenodd%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218px%22%20height%3D%2216px%22%20viewBox%3D%220%200%2018%2016%22%3E%0A%20%20%3Cpath%20fill%3D%22%23666%22%20d%3D%22M0%2C16h8V9H0V16z%20M10%2C16h8V9h-8V16z%20M0%2C7h8V0H0V7z%20M10%2C0v7h8V0H10z%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218px%22%20height%3D%2216px%22%20viewBox%3D%220%200%2018%2016%22%3E%0A%20%20%3Cpath%20fill%3D%22%23333%22%20d%3D%22M0%2C16h8V9H0V16z%20M10%2C16h8V9h-8V16z%20M0%2C7h8V0H0V7z%20M10%2C0v7h8V0H10z%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218px%22%20height%3D%2216px%22%20viewBox%3D%220%200%2018%2016%22%3E%0A%20%20%3Cpath%20fill%3D%22%23111%22%20d%3D%22M0%2C16h8V9H0V16z%20M10%2C16h8V9h-8V16z%20M0%2C7h8V0H0V7z%20M10%2C0v7h8V0H10z%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2222px%22%20height%3D%2213px%22%20viewBox%3D%220%200%2022%2013%22%3E%0A%20%20%3Cpath%20fill%3D%22%23666%22%20d%3D%22M2.75%2C5H10V0H4.4L2.75%2C5z%20M0%2C13h10V7H2L0%2C13z%20M20%2C7h-8v6h10L20%2C7z%20M17.6%2C0H12v5h7.25L17.6%2C0z%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2222px%22%20height%3D%2213px%22%20viewBox%3D%220%200%2022%2013%22%3E%0A%20%20%3Cpath%20fill%3D%22%23333%22%20d%3D%22M2.75%2C5H10V0H4.4L2.75%2C5z%20M0%2C13h10V7H2L0%2C13z%20M20%2C7h-8v6h10L20%2C7z%20M17.6%2C0H12v5h7.25L17.6%2C0z%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.
data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2222px%22%20height%3D%2213px%22%20viewBox%3D%220%200%2022%2013%22%3E%0A%20%20%3Cpath%20fill%3D%22%23111%22%20d%3D%22M2.75%2C5H10V0H4.4L2.75%2C5z%20M0%2C13h10V7H2L0%2C13z%20M20%2C7h-8v6h10L20%2C7z%20M17.6%2C0H12v5h7.25L17.6%2C0z%22%2F%3E%0A%3C%2Fsvg%3E%0A:-1Resource interpreted as Image but transferred with MIME type image/svg+xml.

**Comment by fabio-pisto** [comment]
Hi,
i solved by installing the latest version of qgis

**Comment by fabio-pisto** [comment]
Enrico Thank you very much for your plug in, is fantastic I used often at work, I have a good pc with a video card (GeForce GTX 970 OpenCL 1.2 CUDA) but how can I speed up the loading of the images in the go2streetview window? the plug in use the video card? Thank you

**Comment by enricofer** [comment]
I'm now seeing what happened.
Google released googlemaps.js  as stable the release 3.34 that unfortunately become incompatible with the bugged and discontinued QtWebKit4 used by QGIS 2.18
Now I manually set the plugin to download the last supported release v3.33: https://github.com/enricofer/go2streetview/commit/a4d9984469f9bd7558d85d1d42331c8b4102883a
but there will be no hope after mid february: https://developers.google.com/maps/documentation/javascript/versions
I just submitted the supposed last 2.18 plugin release to Repository...
