### ISSUE TITLE
QGIS 2.18 issue

### ISSUE THREAD

**Issue by jaitor1** [enricofer/go2streetview#44]
Streetview is not loading in QGIS 2.18.
go2streetview version 7.6
Worked fine for months until last week...

![image](https://user-images.githubusercontent.com/12136796/54678300-1aea6780-4b05-11e9-896e-13cd10458d37.png)

Console is showing:

![image](https://user-images.githubusercontent.com/12136796/54678371-5127e700-4b05-11e9-883f-4bed88c8576c.png)

Any ideas?

**Comment by enricofer** [comment]
NOPE https://github.com/enricofer/go2streetview/issues/42#issuecomment-439107758
end of life cycle
