### ISSUE TITLE
API error: RefererNotAllowedMapError

### ISSUE THREAD

**Issue by ArnaudC-10** [enricofer/go2streetview#46]
Hello,
I have done all the process you describe to add the API key to your Qgis plugin, perhaps the screen stay grey with a error message.
![Go2StreetView error](https://user-images.githubusercontent.com/52952426/61275603-97890c00-a7ae-11e9-8c08-facc8a8ec64b.jpg)

When I look in console the message is : 
Google Maps JavaScript API error: RefererNotAllowedMapError
https://developers.google.com/maps/documentation/javascript/error-messages#referer-not-allowed-map-error
Your site URL to be authorized: __file_url__//C:/Users/courcoux/AppData/Roaming/QGIS/QGIS3/profiles/default/python/plugins/go2streetview/res/g2sv.html?lat=48.291933071526564&long=4.14887683796246&width=800&height=268&heading=117&APIkey=mykey

Here is my config API
![Config API](https://user-images.githubusercontent.com/52952426/61276426-4e39bc00-a7b0-11e9-896b-64c71055f939.jpg)

Can you help me ?
Thanks for all

**Comment by enricofer** [comment]
did you insert key in about plugin dialog?
[image: Screenshot 2019-07-16 11.46.20.png]

Il giorno mar 16 lug 2019 alle ore 09:59 ArnaudC-10 <
notifications@github.com> ha scritto:

**Comment by ArnaudC-10** [comment]
Yes I did

**Comment by enricofer** [comment]
I'm looking into https://stackoverflow.com/questions/35288250/google-maps-javascript-api-referernotallowedmaperror
where a comment stated that referrer slot "is supposed to be an optional property and if it blank it should work" almost for localhost.

**Comment by ArnaudC-10** [comment]
I also read this forum but it's not possible to let the refferer blank, and don't know what refferer put.
I don't have localhost because Qgis is only in my computer.
I read since 16 july 2018, we should pay to use StreetView API ! Is it true ?
