### ISSUE TITLE
go2streetview just gone all white:  Google Streetview service unknown error. The request can't be processed.

### ISSUE THREAD

**Issue by denchat** [enricofer/go2streetview#49]
Today, go2streetview just gone all-white.

```
<body style="margin:0">
<div id="zeroResultMessage">Google Streetview service can't find panorama for the specified location</div>
<div id="serviceErrorMessage">Google Streetview service unknown error. The request can't be processed</div>
<div id="g2StreetViewContenitore">
<div id="g2StreetView">
<div name="pano" id="pano"></div>
</div>
</div>
<div id="position_cell">(0,0)</div>
<div id="heading_cell">999</div>
<div id="pitch_cell">0.0</div>
<div id="zoom_cell">40.0</div>
<div id="pano_address">&nbsp;</div>
<div id="pov">POV CONTENT</div>
<div id="json">JSON CONTENT</div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3&amp;key=******&amp;callback=initialize"></script></body>
```

First, I thought there was something wrong in `API` keys.

So I went to `console` and found a yellow sign. I added a restriction to `Map Javascript API` then it turned green checked.

Unfortunately, it didn't help. By the way, It still worked a couple days ago.

**Comment by enricofer** [comment]
There is something related to last QtWebkit release. Consider not to upgrade QGIS for now if you need go2streetview plugin for your work

**Comment by enricofer** [comment]
Try downgrade QtWebkit to 5.9 by Osgeo4W setup

**Comment by denchat** [comment]
QGIS 3.10 causes this. Now back to QGIS 3.8.3. 
I'll try Osgeo4W's QtWebkit 5.9.
Thank you very much.

**Comment by enricofer** [comment]
I can get the plugin running downgrading QtWebkit from 5.221-1 to 5.9 from Osgeo4W installer:
![Screenshot 2019-10-29 18 32 01](https://user-images.githubusercontent.com/7544963/67840590-81515280-faf6-11e9-85a6-14f0c547c237.png)

**Comment by enricofer** [comment]
I opened a QGIS issue ticket: https://github.com/qgis/QGIS/issues/32507
