### ISSUE TITLE
Info Layer Not Showing for Line Type

### ISSUE THREAD

**Issue by Nosscc** [enricofer/go2streetview#51]
Hi Enricofer,

I'm using v8.1 and QGIS 3.4, I've tried adding info layer for point layer and it showed red markers and worked great. However when I change it to layer with line geometry, nothing shows up in the street view, no default blue line anywhere. 
I have also tried using my own icon path which worked for point layer, again it didn't show up for line layer. 
Then I tried to print "tmpfile" and "JS" for line layer, they seemed to have been generated correctly with lots of values and fields.
Could you please help me out?

**Comment by Nosscc** [comment]
Hi Enricofer again,

I've checked everything I could still can't find what caused the issue. I found a small typo in "g2sv.html", below `streetviewOverlay.prototype.draw` where has 
`context.strokeStyle = "FFBB00"`
Then I added "#" in front of stroke color, but still the lines are not showing in the street view panorama. It works for 2D google map view though, only street view has this issue.

Is anyone else experiencing the same problem or just me?

Any advice would be appreciated please

**Comment by enricofer** [comment]
this is partially fixed erasing two lines https://github.com/enricofer/go2streetview/commit/77403503ebd449f2422497f785d9ce77071ed332
but there is a collateral issue becuase when the info layer is loaded panning the image became disabled so you have to manually activate pan an zoom control from options menu

**Comment by Nosscc** [comment]
thanks a lot yes the lines are showing now
apart from the pan zoom control, another issue now is the street view (linestring type) does not display "info field" when hovering mouse over them

**Comment by enricofer** [comment]
This is probably a related issue, because the click event propagation is lost. Further investigation is needed.
