### ISSUE TITLE
[3.11-dev] DeprecationWarning: QgsCoordinateReferenceSystem constructor is deprecated

### ISSUE THREAD

**Issue by denchat** [enricofer/go2streetview#52]
QGIS 3.11.0-59 Nightly warns of go2streetview:

>     WARNING    warning:C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2streetview\go2streetview.py:621: DeprecationWarning: QgsCoordinateReferenceSystem constructor is deprecated
>                   crsSrc = core.QgsCoordinateReferenceSystem(4326) # WGS 84
>                  
>                  traceback: File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2streetview\go2streetview.py", line 466, in setPosition
>                   actualSRS = self.transformToCurrentSRS(actualWGS84)
>                   File "C:/Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\go2streetview\go2streetview.py", line 621, in transformToCurrentSRS
>                   crsSrc = core.QgsCoordinateReferenceSystem(4326) # WGS 84

**Comment by sarahcoathup** [comment]
This is also possibly causing the following message to be displayed in qgis 3.16.9:
WARNING    Used a ballpark transform from EPSG:4326 to EPSG:27700

with the following details:
An alternative, ballpark-only transform was used when transforming coordinates between EPSG:4326 - WGS 84 and EPSG:27700 - OSGB36 / British National Grid. The results may not match those obtained by using the preferred operation:
Possibly an incorrect choice of operation was made for transformations between these reference systems. Check the Project Properties and ensure that the selected transform operations are applicable over the whole extent of the current project.
