### ISSUE TITLE
Using plugin gives Eiffel Tower in Paris

### ISSUE THREAD

**Issue by filipmahieu** [enricofer/go2streetview#54]
What address you try to reach, since shortly you get redirected to the Eifel Tower in Paris..

**Comment by enricofer** [comment]
??? I'm currently testing on QGIS 3.12 on windows 10 without any problem. Previous webkit connection issues seem solved.
Please provide detailed steps to reproduce issue (datasets, platform, settings..)

**Comment by frugardc** [comment]
I am also experiencing this issue.  QGIS 3.8.2

**Comment by filipmahieu** [comment]
I am mistaken, I'm using another pluging, named 'Street View'. Maybe @frugardc  too?

**Comment by frugardc** [comment]
> I am mistaken, I'm using another pluging, named 'Street View'. Maybe @frugardc too?

I think you are right, someone changed them around here.

**Comment by filipmahieu** [comment]
This problem was addressed to the wrong plugin.
Sorry about that
