### ISSUE TITLE
Problem plugin go2streetview

### ISSUE THREAD

**Issue by adnera** [enricofer/go2streetview#55]
Since I updated the "go2streetview" plugin it doesn't work anymore. I generated the API key as required but it reports that there are problems. who can help me?
![Cattura](https://user-images.githubusercontent.com/66955062/84661249-5cd9a780-af1a-11ea-8999-6cbe8a61d19d.PNG)

**Comment by enricofer** [comment]
can you specify platform, qgis and qt version? (You can find infos in menus/about)
Could you provide qtwebkit console trace (plugin options/show web inspector for debugging)
https://github.com/enricofer/go2streetview/issues/31

**Comment by adnera** [comment]
Hi, thanks for the reply.
However I have tried both in Qgis 3.10.3, and in qgis 3.12.3 always with the usual error code. He asks me to set up a payment method to use the API but I never had to pay to use this plugin!
![Cattura](https://user-images.githubusercontent.com/66955062/84746086-c064e300-afb5-11ea-950e-1b31f945bdd8.PNG)

**Comment by enricofer** [comment]
The bad news is that Google updated the terms of service and now require a mean of payment and billing details to activate the API key.
Fortunately the free API usage quotas are very large for a personal use: https://cloud.google.com/maps-platform/pricing/sheet?hl=it at least for now.
At the moment I never have been invoiced.

**Comment by csorin2** [comment]
Hi, 
I had the same problem with qgis 3.10.5 and I solve the problem by add my credit cart for the billing. I think it's the only way now... I hope I will stay under the free quotas
