### ISSUE TITLE
Problem kml street view

### ISSUE THREAD

**Issue by adnera** [enricofer/go2streetview#56]
I have kml files that I can see on google eart and street view, the problem is that when I load the same data on the google earth app, I see them in 3d and 2d but not when I go down in street view while before I saw them. Where am I wrong? 

![Immagine3](https://user-images.githubusercontent.com/66955062/85743030-03386080-b704-11ea-984e-6442cecfe58a.png)

**Comment by enricofer** [comment]
I don't understand how this issue is related to go2streetvie plugin?
