### ISSUE TITLE
Terms of service acceptation dialog frozen

### ISSUE THREAD

**Issue by haubourg** [enricofer/go2streetview#6]
Hi, 
in both 2.6.1 and 2.4 here, I can"t get the plugin to work because the dialog for terms of service does nothing. I can't click in checkboxes, nor click on urls. I can disable the plugin anyway, qgis is not frozen..
Any idea?

**Comment by enricofer** [comment]
New version 5.1 released with modified behaviour of terms of service dialog. it does not appears anymore during plugin initialization but only at first use. 
Menu icon now toggle on/off dockwidget.
