### ISSUE TITLE
get_streetview_url doesn't work with atlas layout

### ISSUE THREAD

**Issue by Theogron** [enricofer/go2streetview#63]
Hello,

I am trying to use the function get_streetview_url(1) with qgis.

I have a multipolygon layer (buildings). I have created a new layout wih an atlas in qgis.

I am trying to configure an oriented street view picture of my buildings with the function  get_streetview_url(1) incremented in an HTML objetct.

Unfortunately, the response is always the same : 'no imagery for location'

Am i using it well ?

![image](https://user-images.githubusercontent.com/97178883/158424207-7316f6ac-085a-4323-b59f-7fe4c8ccf1ba.png)

**Comment by enricofer** [comment]
the expression function basically creates a streetview static view looking to the centroid of the provided geometry from the nearest site covered by streetview service. It makes use of getNearestSVLocation js api method from within the html page: https://github.com/enricofer/go2streetview/blob/9c6646d76de8557de635c1ff6cc8b6638e0f5923/go2streetview.py#L410 [getPanorama](https://github.com/enricofer/go2streetview/blob/9c6646d76de8557de635c1ff6cc8b6638e0f5923/res/g2sv.html#L196)
If the expression is returning  'no imagery for location' maybe google car is not passed by that site or the centroid of a big requested polygon is too far from covered streets.
Try to verify this enabling coverage layer and using a not too far target geometry

**Comment by Theogron** [comment]
Thank you for your quick answer :)

I have made a test and have created litlles polygons just near from a verified street-view point.

The results in Qgis atlas are the sames as i have mentioned in my previous coment.

![image](https://user-images.githubusercontent.com/97178883/158430915-7b455e34-3976-4556-8dd7-2c418c1f965e.png)

![image](https://user-images.githubusercontent.com/97178883/158431316-21cb0ba4-584a-487f-9cb9-035da239ec9b.png)

**Comment by enricofer** [comment]
Static url generator needed some care. here is the fix: https://github.com/enricofer/go2streetview/commit/213ce3868467d1ae50f905f474c2dbbc40542a5a And now the static url is correctly generated.
Now you should reload the plugin from github master source.
Keep in mind that something changed in streetview static api that now has to be explicity enabled, and you have to give some annoying permissions on google api console.

Thanks for submission.

**Comment by Theogron** [comment]
Thank you very much for your answer and your sharing :)

**Comment by Theogron** [comment]
Sory but i have a problem with the installation of the last release from
https://github.com/enricofer/go2streetview/releases

![image](https://user-images.githubusercontent.com/97178883/158812359-e66f9756-b1c7-4759-8107-8c4c86beb9aa.png)

**Comment by enricofer** [comment]
you have to rename the folder from go2streeview-8 to go2streeview

**Comment by enricofer** [comment]
follow the gudelines for installing a plugin https://docs.qgis.org/3.22/it/docs/pyqgis_developer_cookbook/plugins/index.html#developing-plugins

**Comment by Theogron** [comment]
Thank you.
The instalation succeed with the modified name.

I modified the 2 docs you've fixed and ziped the folder to instal it with the qgis console extension.

 Still have the same message 'no imagery for location'.

Must be a wrong way to run it. I'll dig it and find the problem later.

Thank you for your time!

**Comment by Theogron** [comment]
Hello,

Sorry to bother you again. Ihve tried to use again get_street_view url in QGIS.

The plugin is well installed with the last version.

But still have  the same message 'no imagery for location' in results.

Is it working on your side ?
