### ISSUE TITLE
problems with display of streeView images 

### ISSUE THREAD

**Issue by anvalanz** [enricofer/go2streetview#70]
I have been using the plugin for several years without problems.

Today I have reinstalled the plugin and I am facing a problem.

I am unable to correctly display the  streetView image (file_01.JPG) while the map image is working properly (file_02.JPG)

I am using QGIS 3.16.16  on Windows 7.
The version of the plugin is  8.6.

Please note in the lower left corner of the screenshot the icon of a keyboard (which I haven't never seen before), could depend on this ?

Regards 
Antonio Valanzano

![file_01](https://user-images.githubusercontent.com/6723429/185618079-62e3a1e9-9ea4-4be8-be11-72889b0a62ac.JPG)

![file_02](https://user-images.githubusercontent.com/6723429/185618089-0e24bcf8-9cfb-463a-b18f-e2dc737ed36b.JPG)

**Comment by anvalanz** [comment]
Is the plugin development still active or  is it dead?

**Comment by enricofer** [comment]
Can you check in OSGEO4W installer your QtWebkit Version?
![Screenshot (143)](https://user-images.githubusercontent.com/7544963/234505375-41353248-7ebc-45ed-ba63-9341cc142a2f.png)

**Comment by anvalanz** [comment]
Per ora ho installato QGIS 3.22 dall'installer standalone perchè la
versione OSGEO4W mi ha dato problemi.

Posso fare qualche altra prova ?

Antonio


Il giorno mer 26 apr 2023 alle ore 09:44 enrico ferreguti <
***@***.***> ha scritto:

**Comment by enricofer** [comment]
You can anyway check QtWebkit version through osgeo4w setup under QGIS folder in start menu
If you find a qtwebkit version newer than 5.212.0 try to downgrade it
![Screenshot (144)](https://user-images.githubusercontent.com/7544963/234539946-4b002d5f-3e06-4ba9-bbbe-e5d345e7b30a.png)

**Comment by anvalanz** [comment]
I have been able to install QGIS 3.28 LTR with the network installer but
the situation is always the same (black screen for streetview images).

I attach a screenshot of the osgeo4w setup showing that the installed
version of the qtwebkit-libs is 5.212.0

Let me know if I can do more attempts.

Antonio
