### ISSUE TITLE
TypeError: qRegisterResourceData(int, bytes, bytes, bytes): argument 2 has unexpected type 'str'

### ISSUE THREAD

**Issue by J-Southwell** [enricofer/go2streetview#73]
Installing go2streetview on QGIS 3.28.6 gives the following error:

TypeError: qRegisterResourceData(int, bytes, bytes, bytes): argument 2 has unexpected type 'str'

![image](https://github.com/enricofer/go2streetview/assets/135824049/ebce5a5e-813c-4c9a-b491-9377ca2b7ae5)

**Comment by lucadelu** [comment]
It seems related to qgis2web plugin, I got the same error with another plugin and I found other tickets with the same problem. Removing qgis2web this error disappear.
