### ISSUE TITLE
Options selected not persistent

### ISSUE THREAD

**Issue by Fabien98** [enricofer/go2streetview#74]
Firstly, Thanks for this very nice plugin, one of the best in QGIS I use regularly.  👍 

I would like to point out a small bug.
Whenever I tick an option in the plugin window.
(for example : "_Display acquisition date streetview_")
It's note persistent when I close QGIS and I reopen it.
I have to tick again the option the next time.

Also in the options
if we tick "StreetView Coverage" the layer is displayed even when the plugin is closed.
Would be nice to to display this layer only when the plugin is activated.

====Versions
Version Go2streetview : 8.6
QGIS 3.22.7
Windows 10

**Comment by enricofer** [comment]
https://github.com/enricofer/go2streetview/commit/2f6efe15f2e8585269cee451cf57bbda44c76ce2
