### ISSUE TITLE
How to rotate the display to 360 degrees?

### ISSUE THREAD

**Issue by image80** [enricofer/go2streetview#76]
Good afternoon,
is it possible to rotate the display to 360 degrees (as can be done in a classic google maps web page interface ?)
Moreover, what is the option called "Add an layer information" ?  In my opinion, the plugin deserves more detailed/updated documentation.I must confess my current experience with the plugin on qubuntu (linux) is a bit unstable and slow. it's almost unusable on myside.

**Comment by enricofer** [comment]
feel free to improve it
