### ISSUE TITLE
"Google Streetview service can't find panorama for the specified location"

### ISSUE THREAD

**Issue by J-Southwell** [enricofer/go2streetview#77]
![MicrosoftTeams-image](https://github.com/enricofer/go2streetview/assets/135824049/bd762184-2142-407d-8fde-c4580a408253)

The plugin is currently not working as expected & is crashing QGIS 3.28 Firenze.

**Comment by Apimente3** [comment]
Please, someone knows about this issue and how to solved, thanks in advance...!!

**Comment by cm0001** [comment]
I have the same error.



QGIS version
3.28.12-Firenze
QGIS code revision
dcc633b2de
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.8.0
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009




Active Python plugins
coordinate_capture
0.2
geometry_paster
0.2
Go2NextFeature3
2.1
Go2NextFeaturePlus
3.0
go2streetview
8.6
HCMGIS
23.7.19
Hotlink
0.8.6
LAStools
1.5
latlontools
3.6.16
mmqgis
2021.9.10
numericalDigitize
0.4.7
QlrBrowser
3.0.0
QuickWKT
3.1
quick_map_services
0.19.33
searchlayers
3.0.14
SpreadsheetLayers
2.1.0
vectorflip
0.1
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

**Comment by yvo2m** [comment]
https://stackoverflow.com/questions/76989163/loading-google-maps-a-weird-error-uncaught-syntaxerror-unexpected-token-in

Open the g2sv.html file (for windows in AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\go2streetview\res )

modify the line 63 : force api version to v3.53 (instead of v3)

`function loadScript() {
  var script = document.createElement('script');
  script.type = 'text/javascript';
  script.src = 'https://maps.googleapis.com/maps/api/js?v=3.53' +
      '&key=' + APIkey_param +'&callback=initialize';
  document.body.appendChild(script);
}`

**Comment by andreaaz83** [comment]
seguo

**Comment by albertograva** [comment]
I confirm the problem

Versione di QGIS | 3.34.0-Prizren | Revisione codice QGIS | ffbdd678812
Versione Qt | 5.15.3
Versione Python | 3.10.12
Versione GDAL/OGR | 3.4.1
Versione PROJ | 8.2.1
Versione database del Registro EPSG | v10.041 (2021-12-03)
Versione GEOS | 3.10.2-CAPI-1.16.0
Versione SQLite | 3.37.2
Versione PDAL | 2.3.0
Versione client PostgreSQL | 14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
Versione SpatiaLite | 5.0.1
Versione QWT | 6.1.4
Versione QScintilla2 | 2.11.6
Versione SO | Ubuntu 22.04.3 LTS
  
Plugins Python attivi
Mergin | 2023.4.1
shapetools | 3.4.14
slyr_community | 5.0.0
IRDATExplorer | 3.0.2
QuickOSM | 2.2.3
QuickMultiAttributeEdit3 | version 3.0.3
qmapshaper | 0.8.2
processing_saga_nextgen | 1.0.0
go2streetview | 8.6
grassprovider | 2.12.99
db_manager | 0.1.20
processing | 2.12.99

**Comment by J-Southwell** [comment]
> https://stackoverflow.com/questions/76989163/loading-google-maps-a-weird-error-uncaught-syntaxerror-unexpected-token-in
> 
> Open the g2sv.html file (for windows in AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\go2streetview\res )
> 
> modify the line 63 : force api version to v3.53 (instead of just v3)
> 
> ```js
> function loadScript() {
>   var script = document.createElement('script');
>   script.type = 'text/javascript';
>   script.src = 'https://maps.googleapis.com/maps/api/js?v=3.53' +
>       '&key=' + APIkey_param +'&callback=initialize';
>   document.body.appendChild(script);
> }
> ```

This has worked for me.

**Comment by yvo2m** [comment]
@J-Southwell the issue should not be closed until fix is pushed in depository, please reopen.

**Comment by J-Southwell** [comment]
@yvo2m Sorry! Re-opened now. Thank you again.

**Comment by Welshmilla** [comment]
That works, but it looks like version 3.53 might be removed after February 2024, so a more permanent fix will be needed

https://developers.google.com/maps/documentation/javascript/versions

**Comment by enricofer** [comment]
I all, thanks for all your contributions and submissions.
I will soon publish a patch with the last running version of google maps api, but I fear that this will be the last.
Unfortunately the QGIS supported QtWebkit is obsolete https://blogs.gnome.org/mcatanzaro/2022/11/04/stop-using-qtwebkit/ and we will need to wait for Qt6 - QtWebEngine support in the nextcoming QGIS4

**Comment by glorenzetto** [comment]
> > https://stackoverflow.com/questions/76989163/loading-google-maps-a-weird-error-uncaught-syntaxerror-unexpected-token-in
> > Open the g2sv.html file (for windows in AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\go2streetview\res )
> > modify the line 63 : force api version to v3.53 (instead of just v3)
> > ```js
> > function loadScript() {
> >   var script = document.createElement('script');
> >   script.type = 'text/javascript';
> >   script.src = 'https://maps.googleapis.com/maps/api/js?v=3.53' +
> >       '&key=' + APIkey_param +'&callback=initialize';
> >   document.body.appendChild(script);
> > }
> > ```
> 
> This has worked for me. Thank you very much to @yvo2m

this work for me too, thx

**Comment by enricofer** [comment]
I submitted the new v8.7 release to plugins.qgis.org and I'm waiting for approval.
In the meanwhile you can download and load as zip: https://github.com/enricofer/go2streetview/archive/refs/tags/8.7.zip
