### ISSUE TITLE
Mau funcionamento

### ISSUE THREAD

**Issue by lariraujo** [enricofer/go2streetview#81]
Olá
Há alguns dias o plugin não esta funcionando, minha equipe utiliza algumas versões diferentes do qgis além de chave api diferentes, em todo caso, nos posicionamos o cursor na tela e a resposta é em branco, tentei instalar o complemento baixando pelo sit e instalando modo zip, também sem sucesso. 

aguardo retorno

**Comment by enricofer** [comment]
A patched release v8.7 has been published.
upgrade through plugin menu

**Comment by enricofer** [comment]
https://github.com/enricofer/go2streetview/issues/77
