### ISSUE TITLE
Issues with the dirpath plugin

### ISSUE THREAD

**Issue by Rarzabe** [enricofer/go2streetview#83]
When I activate the plugin in the viewer I get a black screen, and I noticed that in the Qgis messages, the file address is incorrect. How can I fix the code to solve this error?
![Captura de pantalla 2024-04-04 171056](https://github.com/enricofer/go2streetview/assets/166065995/141fc350-05d1-44f7-b911-af570c38db15)

I am using Qgis version 3.36.1 for Windows
When I correct the address in my browser it works
![Captura de pantalla 2024-04-04 171724](https://github.com/enricofer/go2streetview/assets/166065995/1374a497-d837-4c0f-a185-fccefbe634e5)

Thank's

**Comment by yvo2m** [comment]
I don't think the problem is in the path. 
If you revert QGIS to 3.34.5 you will have the same message but no issue.

You will see the real error by opening the web inspector (open it, by clicking on the lines button menu at the top right of the go2streetview window)

**Comment by Rarzabe** [comment]
@yvo2m I downgraded the program version to LTR and it worked without problems. Thanks for the help.
