### ISSUE TITLE
cannot import name 'QtWebKit' from 'PyQt5'

### ISSUE THREAD

**Issue by smblnts21** [enricofer/go2streetview#84]
1 aur/python-pyqt5-webkit 5.15.10-1 (+3 0.00) (Huérfano) 
    A set of Python bindings for the Qt5 toolkit with Qt5WebKit support

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/qgis/utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexander/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2streetview/__init__.py", line 34, in classFactory
    from .go2streetview import go2streetview
  File "/home/alexander/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ee_plugin/__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alexander/.local/share/QGIS/QGIS3/profiles/default/python/plugins/go2streetview/go2streetview.py", line 22, in 
    from PyQt5 import Qt, QtCore, QtWidgets, QtGui, QtWebKit, QtWebKitWidgets, QtXml, QtNetwork, uic
ImportError: cannot import name 'QtWebKit' from 'PyQt5' (/usr/lib/python3.12/site-packages/PyQt5/__init__.py)

**Comment by kikislater** [comment]
QtWebKit is deprecated due to lack of support, security problems and replaced by QWebview
This plugin needs update to convert from QtWebkit to QWebView. Almost all others plugins have moved ...

**Comment by smblnts21** [comment]
With the new version of QGIS, the movement of Atlas was corrected, however the HTML part does not appear Warning: KServiceTypeTrader: serviceType "ThumbCreator" not found

**Comment by enricofer** [comment]
Qt Webkit is dropped for Qt WebEngine. Check new plugin version on QGIS 3.36

**Comment by smblnts21** [comment]
Critical: Uncaught TypeError: Cannot read property 'setCenter' of undefined
Critical: Uncaught TypeError: Cannot read property 'setOptions' of undefined
Critical: Uncaught TypeError: Cannot read property 'setPosition' of undefined
Critical: Uncaught TypeError: this.clearMarkers is not a function
Critical: Uncaught TypeError: this.clearMarkers is not a function
Warning: setGrabPopup called with a parent, QtWaylandClient::QWaylandXdgSurface(0x55d332d4f9f0) which does not match the current topmost grabbing popup, QtWaylandClient::QWaylandXdgSurface(0x55d337996a10) According to the xdg-shell protocol, this is not allowed. The wayland QPA plugin is currently handling it by setting the parent to the topmost grabbing popup. Note, however, that this may cause positioning errors and popups closing unxpectedly because xdg-shell mandate that child popups close before parents
