### ISSUE TITLE
"Google Streetview service can't find panorama for the specified location"

### ISSUE THREAD

**Issue by Herbert-Khrill** [enricofer/go2streetview#88]
Hi there,
It doesn't work anymore for me (used to work fine).
The debug  windows says it can't find a panorama even though it is covered by streetview :
![image](https://github.com/enricofer/go2streetview/assets/60649837/b73b9bb9-338f-4473-ab06-11d818126507)

thanks

**Comment by enricofer** [comment]
https://github.com/enricofer/go2streetview/issues/87#issuecomment-2132114322

Il Lun 27 Mag 2024, 16:39 Herbert-Khrill ***@***.***> ha
scritto:

**Comment by Herbert-Khrill** [comment]
Thank you, I didn't see it.
Just hopping and waiting for the new version then.
Thank you

**Comment by enricofer** [comment]
I submitted a first Qt WebEngine implementation available from QGIS 3.36 : https://github.com/enricofer/go2streetview/tree/v10
Please test is and report bugs

**Comment by enricofer** [comment]
The new plugin version is now published
