### ISSUE TITLE
problem to view go2treetview

### ISSUE THREAD

**Issue by iadobat** [enricofer/go2streetview#9]
sorry for my bad English ...
My problem is the inability to see the streetview in the window of qgis and also connected in the browser.
I realized that I refer to in the browser streetview with coordinates 0.0.
, Despite being placed on the map of Italy.
With Bing works well
Op system OSX 10.10.3 with qgis 2.8

Giovanni Morello

**Comment by iadobat** [comment]
Console Python 
Usa iface per accedere all'interfaccia API QGIS oppure digita help(iface) per le informazioni
qrc:///plugins/go2streetview/res/g2sv.html?lat=44.4144109541&long=8.92422236191&width=361&height=355&heading=0
http://dev.virtualearth.net/embeddedMap/v1/ajax/Birdseye?zoomLevel=17&center=44.4144109541_8.92422236191&heading=0
qrc:///plugins/go2streetview/res/g2sv.html?lat=44.4158738081&long=8.92940990624&width=361&height=355&heading=37
http://dev.virtualearth.net/embeddedMap/v1/ajax/Birdseye?zoomLevel=17&center=44.4158738081_8.92940990624&heading=0
qrc:///plugins/go2streetview/res/g2sv.html?lat=44.4188886614&long=8.93209966765&width=361&height=355&heading=0
http://dev.virtualearth.net/embeddedMap/v1/ajax/Birdseye?zoomLevel=17&center=44.4188886614_8.93209966765&heading=0

**Comment by enricofer** [comment]
As we need to exclude connection errore I need you to install a Development Version with witch gives debugging information. Download zipped plugin from https://github.com/enricofer/go2streetview/archive/v6_connection_debug.zip then extract the content in go2streetview folder located under Your home dir in [home dir]/.qgis/python/plugin/go2streetview
Then restart qgis, open python console and send back runtime messages

**Comment by iadobat** [comment]
I replaced the folder and it says that the plugin is corrupt

**Comment by iadobat** [comment]
questo è ol link che tiro fuori dal browser:
https://www.google.com/maps/@0,0,3a,75y,999h,90t/data=!3m3!1e1!3m1!2e0

**Comment by iadobat** [comment]
questo è ol link che tiro fuori dal browser:
https://www.google.com/maps/@0,0,3a,75y,999h,90t/data=!3m3!1e1!3m1!2e0

**Comment by iadobat** [comment]
this is ol link that shot out of the browser:
https://www.google.com/maps/@0,0,3a,75y,999h,90t/data=!3m3!1e1!3m1!2e0

**Comment by enricofer** [comment]
1) unzip the file https://github.com/enricofer/go2streetview/archive/v6_connection_debug.zip  and copy the files within the enclosed folder 'go2streetview-6_connection_debug' into [home dir]/.qgis/python/plugin/go2streetview. (and create a folder snapshot)
2) try to point and drag cursor holding CTRL button

**Comment by iadobat** [comment]
cmd with the browser works but the window does not work qgis:

the python console says this:
Console Python 
Usa iface per accedere all'interfaccia API QGIS oppure digita help(iface) per le informazioni
206 264
qrc:///plugins/go2streetview/res/g2sv.html?lat=44.4111144543&long=8.93361115912&width=206&height=264&heading=90
http://dev.virtualearth.net/embeddedMap/v1/ajax/Birdseye?zoomLevel=17&center=44.4111144543_8.93361115912&heading=90
STREETVIEW OTHER CONNECTION ERROR: 6

**Comment by enricofer** [comment]
Well. A connection issue, A misterious SslHandshakeFailedError. Lets go deeper:
1) download updated https://github.com/enricofer/go2streetview/archive/v6_connection_debug.zip and write it over previous plugin, restart qgis and look to python console.
2) Exactly when does the issue started to occurs? When do you updated qgis? Or plugin?

**Comment by iadobat** [comment]
with the Web Connector plugin happens:
1) I see from his window all but streetview
2) sreetview browser called from web connector works.

**Comment by iadobat** [comment]
The problem appeared after a few weeks ... I do not know if it appeared after an update

**Comment by iadobat** [comment]
It 'a very strange error ... by go2 street appeal if the browser by pressing cmd ... only works from the browser

**Comment by enricofer** [comment]
please feedback python console debug trace with updated development plugin: https://github.com/enricofer/go2streetview/archive/v6_connection_debug.zip

**Comment by iadobat** [comment]
Console Python 
Usa iface per accedere all'interfaccia API QGIS oppure digita help(iface) per le informazioni
191 264
qrc:///plugins/go2streetview/res/g2sv.html?lat=44.4194310463&long=8.88879422158&width=191&height=264&heading=189
http://dev.virtualearth.net/embeddedMap/v1/ajax/Birdseye?zoomLevel=17&center=44.4194310463_8.88879422158&heading=180
Request:
Traceback (most recent call last):
  File "/Users/giovannimorello/.qgis2/python/plugins/go2streetview/go2streetview.py", line 719, in logSslErrors
    print "Request:",reply.request.url(),"SSL errors:",errorList
AttributeError: 'builtin_function_or_method' object has no attribute 'url'
STREETVIEW OTHER CONNECTION ERROR. url:
Traceback (most recent call last):
  File "/Users/giovannimorello/.qgis2/python/plugins/go2streetview/go2streetview.py", line 704, in noSVConnectionsPending
    print "STREETVIEW OTHER CONNECTION ERROR. url:",reply.request.url(),"error:",reply.error()
AttributeError: 'builtin_function_or_method' object has no attribute 'url'

**Comment by iadobat** [comment]
These are the mistakes of Python Console

**Comment by enricofer** [comment]
There were some issues in the code I send you.
Please retry to download/reinstall connection debug version:
https://github.com/enricofer/go2streetview/archive/v6_connection_debug.zip

**Comment by iadobat** [comment]
... but the folder that you've manfato have to replace it with the original program?

**Comment by enricofer** [comment]
just replace the file go2streetview.py with the one provided in the zip file

**Comment by iadobat** [comment]
Console Python 
Usa iface per accedere all'interfaccia API QGIS oppure digita help(iface) per le informazioni
361 264
qrc:///plugins/go2streetview/res/g2sv.html?lat=44.4201703046&long=8.9073516259&width=361&height=264&heading=90
http://dev.virtualearth.net/embeddedMap/v1/ajax/Birdseye?zoomLevel=17&center=44.4201703046_8.9073516259&heading=90
SSL ERROR REQUEST:
Traceback (most recent call last):
  File "/Users/giovannimorello/.qgis2/python/plugins/go2streetview/go2streetview.py", line 719, in logSslErrors
    print "SSL ERROR REQUEST:",reply.request.url().toString(),"REPLY:",reply.url(),"CODE:",errorList
AttributeError: 'builtin_function_or_method' object has no attribute 'url'
STREETVIEW OTHER CONNECTION ERROR. REQUEST: https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false REPLY: https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false CODE: 6

**Comment by iadobat** [comment]
i don't closed

**Comment by enricofer** [comment]
Could you try the last development release to verify if the issues you reported are fixed?
I redeveloped connections procedure and fixed some bugs.
https://github.com/enricofer/go2streetview/archive/master.zip

**Comment by enricofer** [comment]
fixed

**Comment by jonywoker** [comment]
Sorry to bother you but can you help me out. I am trying to change the icon using the icon path , i used on the fields  using the field calulcator which directs to the column with the file path but it does not show up. Is there a specific type of file jpg png svg that will work . i can only see the google default one. The other question is regarding the html . I tried the html to pull up a picture it worked find when looking for a picture online but i wanted to pull it out locally and had it saved in a variable but it won't work can you please check this 


<table style="width:100%">
  <tr>
    <th>IDCAMPO</th>
    <th>DESCRIPCION</th>
    <th>INEN</th>
  </tr>
  <tr>
    <td>[% "idCampo"%]</td>
    <td>[% "._Field2"%] </td>
    <td>[% "SENALINEN" %]</td>
  </tr>
  <tr>
    <td><img src=[%  "ICON"  %]></td>
    <td>[% "._Field2"%] </td>
    <td>[% "SENALINEN" %]</td>

  </tr>
</table>
 in the part icCampo it works if is an external link but when i used a local path i won't work ..any idea thanks you

**Comment by enricofer** [comment]
You have to point local resources with the following format:
`file:///c:/path_to_image/image.png`
Take care of transforming backslashes to slashes under windows systems
[
https://forum.qt.io/topic/40304/solved-problems-loading-local-content-into-qwebview](url)

2016-07-20 0:56 GMT+02:00 jonywoker <notifications@github.com>:

**Comment by jonywoker** [comment]
thank you very much it worked. I am using Mac file:///Users/Name/Desktop/ but it worked just fine.. thank you the plug in is amazing.
