### ISSUE TITLE
Feature request: option to disable green digitizing dot

### ISSUE THREAD

**Issue by TimoWalraven** [enricofer/go2streetview#91]
First of all, very nice plugin! V10.0 works like a charm after the necessary debugging. 
I have a small feature request, could an option to not show the green dot used for digitizing be added?
I do not need it, and it distracts me during my work. Would be much appreciated. 

Cheers,

Timo

**Comment by enricofer** [comment]
ok. not so hard job.

**Comment by TimoWalraven** [comment]
:) thanks!
